services:
  test-db:
    image: postgres:15-alpine
    ports:
      - "7444:5432"
    env_file: ".env.test"
  dev-db:
    image: postgres:15-alpine
    ports:
      - "6444:5432"
    env_file: ".env"

